version: '3.2'
services:
  api:
    container_name: 'test'
    build:
      context: .
      dockerfile: DockerFile.test
    command: sh -c 'apk add git && rm -rf /var/cache/apk/* && npm install && npm run test'
    tty: true
    environment:
      ENV_SILENT: 'true'
      APP_KEY: 'Q30chr4pFwBsGfBvmWHZAXB4x1JDbZkz'

      DB_CONNECTION: 'pg'
      DB_DATABASE: 'db-test'
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_PORT: '5555'

      DB_HOST: 'dbtest'

      HOST: '127.0.0.1'
      PORT: '4000'
      NODE_ENV: testing
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dbtest
    links:
      - 'dbtest:dbtest'
  dbtest:
    container_name: 'dbtest'
    image: postgres:latest
    environment:
      PGPORT: 5555
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-test
