version: '3.2'
services:
  api:
    container_name: 'app'
    build:
      .
      # context: .
    command: sh -c 'apk add git && rm -rf /var/cache/apk/*  && node ace migration:run && node ace serve --watch'
    tty: true
    environment:
      ENV_SILENT: 'true'
      APP_KEY: 'Q30chr4pFwBsGfBvmWHZAXB4x1JDbZkz'

      DB_CONNECTION: 'pg'
      PG_DB_DATABASE: 'db'
      PG_USER: 'root'
      PG_PASSWORD: 'password'
      PG_PORT: '5432'

      PG_HOST: 'db-app'

      HOST: '0.0.0.0'
      PORT: '3333'
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db-app
    ports:
      - '3333:3333'
  db-app:
    container_name: 'db-app'
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
